# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/python/tags/
image: python:latest

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

# Pip's cache doesn't store the python packages
# https://pip.pypa.io/en/stable/reference/pip_install/#caching
#
# If you want to also cache the installed packages, you have to install
# them in a virtualenv and cache it as well.
cache:
  paths:
    - .cache/pip
    - env/

stages:
  - test

before_script:
  - python -V  # Print out python version for debugging
  - python -m venv env
  - source env/bin/activate

unit_tests:
  stage: test
  script:
    - pip install -r requirements-test.txt
    - git config --global user.email "test_user@test_mail.test"
    - git config --global user.name test_name
    - pytest -x --showlocals tests/

unit_tests_python36:
  extends: unit_tests
  image: python:3.6

build_package:
  stage: test
  script:
    - pip install wheel
    - python setup.py bdist_wheel sdist
  artifacts:
    paths:
      - dist/roboversion*.whl
      - dist/roboversion*.tar.gz

pages:
  stage: test
  script:
    - pip install -r requirements-doc.txt
    - sphinx-build docs/ public
  artifacts:
    paths:
      - public
  when: manual
